### ISSUE TITLE
Waste Collection Request from the Organization

### ISSUE THREAD

**Issue by RavijaSalpitikorala** [LasithRanahewa/trashsmart-server#78]
When the organization is creating a new request do they create the request as a general req. for the whole org. or for a specific bin?
If it is for a bin need to create that endpoint and take count of how they fetch the location of the bin from the backend.
And that req. creating should be only clicking a button and all the other details should be fetched from the bin otherwise no point of creating a req. for a specific bin.

**Comment by rusarabw** [comment]
Waste collection requests are created per bin. Relevant endpoints are developed and tested.
